// <auto-generated />
using System;
using Heroflix.Controllers.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Heroflix.Migrations
{
    [DbContext(typeof(HeroflixContext))]
    partial class HeroflixContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("Heroflix.Models.Filme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AssistidoEm");

                    b.Property<string>("Elenco");

                    b.Property<string>("Genero");

                    b.Property<string>("Sinopse");

                    b.Property<int>("Status");

                    b.Property<string>("Titulo")
                        .HasMaxLength(50);

                    b.Property<string>("UrlCapa");

                    b.HasKey("Id");

                    b.ToTable("Filmes");
                });
#pragma warning restore 612, 618
        }
    }
}
